### PR TITLE
Rename TypeMap to Extensions

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Implements #116. Thanks!

## Screenshots

Screenshot_2020-04-24 http_types - Rust

### CODE REVIEW

**Comment by Fishrock123** [comment]
As a newcomer, this seems more clear. :+1:

**Comment by yoshuawuyts** [comment]
@Fishrock123 the issue I see with the word "local" is that the question becomes: "local to what?" `LocalStorage` may be scoped locally to the thread, runtime, framework, request, endpoint, or middleware. `Extensions` is less overloaded -- at worst it may not be clear *what* it extends, but the assumption will always be that it extends something in the crate -- and good docs can help explain what it does.

**Comment by Fishrock123** [comment]
What about `ContinuationStorage` then?

**Comment by yoshuawuyts** [comment]
@Fishrock123 if, like me, you don't know what a "continuation" is in this context, that name doesn't seem very intuitive. It's also fairly long. "Extensions" is shortened in the codebase as `Request::ext()` and `Response::ext()`. In contrast smth like `Request::cont_store` seems less intuitive to me, but also longer.

I feel overall "extensions" is the best fit we have. With the added benefit that other crates in the Rust ecosystem use the same name for the same concept as well.

**Comment by Fishrock123** [comment]
A bit late, but `async_std` does also use the term "local storage" for tasks, and the api is "LocalKey": https://docs.rs/async-std/1.5.0/async_std/task/index.html#task-local-storage

**Pull request merged**
